In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [6]:
type(mylist)

list

In [8]:
np.array(mylist)

array([1, 2, 3])

In [10]:
type(mylist)

list

In [12]:
arr = np.array(mylist)

In [14]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [18]:
mymatrix = np.array(mylist)

In [21]:
mymatrix.shape

(3, 3)

In [24]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
type(0.)

float

In [30]:
np.zeros((4,10))

#4x10

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [34]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [35]:
[1,1,1,1] * 100

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [37]:
[1,1,1,1] + 10

TypeError: can only concatenate list (not "int") to list

In [40]:
#시계열 데이터를 다룰때 많이 사용

In [42]:
np.ones(4) / 100

array([0.01, 0.01, 0.01, 0.01])

In [43]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [44]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [46]:
np.linspace(0,9,20)

array([0.        , 0.47368421, 0.94736842, 1.42105263, 1.89473684,
       2.36842105, 2.84210526, 3.31578947, 3.78947368, 4.26315789,
       4.73684211, 5.21052632, 5.68421053, 6.15789474, 6.63157895,
       7.10526316, 7.57894737, 8.05263158, 8.52631579, 9.        ])

In [48]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
# part2

In [52]:
np.random.rand(1)
# 0과 1사이 난수

array([0.0114316])

In [53]:
np.random.rand(5,5)
# 0과 1 사이로 있는 난수 구성으로 된 5x5 행렬 표시 

array([[0.28626541, 0.68950374, 0.64363562, 0.02367931, 0.51510978],
       [0.27477052, 0.62640385, 0.24189524, 0.00958671, 0.29062461],
       [0.99547508, 0.4265617 , 0.69655827, 0.80214007, 0.92335448],
       [0.85400412, 0.93898142, 0.8756236 , 0.25999189, 0.5175185 ],
       [0.41211817, 0.98763427, 0.79960299, 0.98343628, 0.00259286]])

In [55]:
np.random.randn(1)

#표준편자 1 평균 0 

array([-0.29879005])

In [64]:
np.random.normal(5,1,1)
#normal(loc=0.0, scale=1.0, size=None)
#평균 , 표준편차, 샘플 사이즈 

array([5.02505862])

In [67]:
np.random.randint(1,100,10)
# 최솟값을 포함하고 최댓값을 제외한 범위에서 임이의 정수 반환

array([78, 50, 98, 40, 76, 86, 27, 56, 43, 48])

In [69]:
np.random.randint(1,100)
# default 1개 

44

In [73]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [74]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [75]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [79]:
arr = np.arange(25)

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [83]:
ranarr = np.random.randint(0,50,10)

In [85]:
ranarr

array([21,  1, 23, 43, 29, 37,  1, 20, 32, 11])

In [86]:
arr.reshape(5,5)
#현재 녀석과 숫자를 맞도록 지정해줘야함

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [88]:
arr.reshape(5,6)
# 위와같은 이유로 이렇게 에러가 뜸뜸 

ValueError: cannot reshape array of size 25 into shape (5,6)

In [95]:
ranarr.max()


43

In [96]:
ranarr.argmax()

3

In [97]:
ranarr.min()

1

In [98]:
ranarr.argmin()

1

In [3]:
ranarr.dtype()


NameError: name 'ranarr' is not defined

# numpy indexing and selection
<!-- 기본적으로 인덱싱을 통해 1차원 배열이나 2차원 배열에서 단일 요소를 선택 -->