In [1]:
import numpy as np

In [4]:
arrs = np.arange(1,10)

In [5]:
arrs + arrs

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
1/arr

NameError: name 'arr' is not defined

In [7]:
1/arrs

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [8]:
arrs/arrs

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.log(arrs)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [13]:
np.sin(arrs)
# 삼각함수 연산 

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [14]:
arrs.sum()

45

In [15]:
arrs.mean()

5.0

In [16]:
arr.max()

NameError: name 'arr' is not defined

In [17]:
arrs.max()

9

In [18]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [19]:
arr_2d.sum()

78

In [20]:
# GIVE ME THE SUM ACROSS THE ROWS
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [21]:
arr_2d.sum(axis=1)

array([10, 26, 42])